### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [Ethylene9160/SUSTC_EE317_Android_applications#1]
hallo，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：)

**Comment by Ethylene9160** [comment]
待窝稍作整理TvT。周二晚上回您。

**Comment by Ethylene9160** [comment]
好酷的EE-Hero仓库！窝整理好楽TvT很荣幸被佬看中（虽然写的很烂ww），希望能帮到下一代（hjh我已经看不明白里边写了什么了）。谢谢大佬光顾-v-

**Comment by drinktoomuchsax** [comment]
respect
